import { useState } from 'react';
import type {
  DatabaseModel, ObjectType, FilterState, ExtensionConfig,
  AnalysisMode
} from '../engine/types';
import type { LoadingPhase } from '../components/VisualizingScreen';

type AppView = 'start' | 'create' | 'visualizing' | 'graph';
import { DEFAULT_CONFIG } from '../engine/types';
import type { Project, FilterProfile, AIViewMetadata } from '../engine/projectStore';

/**
 * Transient AI view — shown as a preview before the user decides to save.
 * 
 * @remarks
 * This interface represents the state of a view generated by the AI assistant.
 * It contains a canonical set of nodes and associated AI metadata (narrative, groups, etc.).
 * It is held in transient state until the user explicitly bookmarks it.
 */
export interface AiPreview {
  /** The name/title of the AI-generated view. */
  name: string;
  /** The set of node IDs that are part of this view. */
  nodeIds: Set<string>;
  /** High-fidelity metadata authored by the AI (descriptions, highlight groups, etc.). */
  aiMetadata: AIViewMetadata;
}

/**
 * State representation for the graph context menu.
 * 
 * @remarks
 * This object captures all metadata required to render the context menu and perform
 * actions on a specific node (e.g., drilling down, opening external links).
 */
export interface ContextMenuState {
  /** X-coordinate on the screen. */
  x: number;
  /** Y-coordinate on the screen. */
  y: number;
  /** The ID of the node being targeted. */
  nodeId: string;
  /** The display name of the node. */
  nodeName: string;
  /** The schema of the target object. */
  schema: string;
  /** Optional classification for external references. */
  externalType?: 'et' | 'file' | 'db';
  /** Optional URL for external documentation or source. */
  externalUrl?: string;
  /** The full three-part name if applicable. */
  fullName?: string;
  /** The primary SQL object type. */
  objectType: ObjectType;
}

/**
 * The primary state orchestration hook for the Data Lineage Viz application.
 * 
 * @remarks
 * This hook acts as the "God Store" for the React frontend, managing everything from
 * navigation views and database models to active filters and loading states.
 * It provides a centralized dispatcher for all UI-driven state changes.
 * 
 * @param isAutoVisualize - Whether the app should immediately enter visualization mode (demo mode).
 * @returns A comprehensive set of state variables and their respective setters.
 */
export function useAppState(isAutoVisualize: boolean) {
  const [view, setView] = useState<AppView>(isAutoVisualize ? 'visualizing' : 'start');
  const [model, setModel] = useState<DatabaseModel | null>(null);
  const [config, setConfig] = useState<ExtensionConfig>(DEFAULT_CONFIG);
  const [projects, setProjects] = useState<Project[]>([]);
  const [lastOpenedId, setLastOpenedId] = useState<string | null>(null);
  const [lastWizardView, setLastWizardView] = useState<'main' | 'projects'>('main');
  const [activeProjectId, setActiveProjectId] = useState<string | null>(null);
  const [activeViewId, setActiveViewId] = useState<string | null>(null);
  const [loadingProjectId, setLoadingProjectId] = useState<string | null>(null);
  const [contextMenu, setContextMenu] = useState<ContextMenuState | null>(null);

  // VisualizingScreen state
  const [loadingPhase, setLoadingPhase] = useState<LoadingPhase>('load');
  const [loadingStats, setLoadingStats] = useState<string | null>(null);
  const [loadingError, setLoadingError] = useState<string | null>(null);
  const [startScreenMessage, setStartScreenMessage] = useState<string | null>(null);

  // Graph source name (for toolbar/export)
  const [sourceName, setSourceName] = useState<string | null>(isAutoVisualize ? 'AdventureWorks (demo)' : null);

  const [filter, setFilter] = useState<FilterState>({
    schemas: new Set(),
    types: new Set<ObjectType>(['table', 'view', 'procedure', 'function', 'external']),
    searchTerm: '',
    hideIsolated: true,
    focusSchemas: new Set(),
    showExternalRefs: true,
    externalRefTypes: new Set<'file' | 'db'>(['file', 'db']),
    exclusionPatterns: [],
  });

  const [isRebuilding, setIsRebuilding] = useState(false);
  const [highlightedNodeId, setHighlightedNodeId] = useState<string | null>(null);
  const [infoBarNodeId, setInfoBarNodeId] = useState<string | null>(null);
  const [isDetailOpen, setIsDetailOpen] = useState(false);
  const [isDetailSearchOpen, setIsDetailSearchOpen] = useState(false);
  const [analysisMode, setAnalysisMode] = useState<AnalysisMode | null>(null);

  const [activeAdvancedProfile, setActiveAdvancedProfile] = useState<FilterProfile | null>(null);
  const [aiPreview, setAiPreview] = useState<AiPreview | null>(null);
  
  // Viewport/Position state for bookmarks
  const [pendingPositions, setPendingPositions] = useState<Record<string, { x: number; y: number }> | undefined>(undefined);
  const [pendingViewport, setPendingViewport] = useState<{ x: number; y: number; zoom: number } | undefined>(undefined);

  return {
    view, setView,
    model, setModel,
    config, setConfig,
    projects, setProjects,
    lastOpenedId, setLastOpenedId,
    lastWizardView, setLastWizardView,
    activeProjectId, setActiveProjectId,
    activeViewId, setActiveViewId,
    loadingProjectId, setLoadingProjectId,
    contextMenu, setContextMenu,
    loadingPhase, setLoadingPhase,
    loadingStats, setLoadingStats,
    loadingError, setLoadingError,
    startScreenMessage, setStartScreenMessage,
    sourceName, setSourceName,
    filter, setFilter,
    isRebuilding, setIsRebuilding,
    highlightedNodeId, setHighlightedNodeId,
    infoBarNodeId, setInfoBarNodeId,
    isDetailOpen, setIsDetailOpen,
    isDetailSearchOpen, setIsDetailSearchOpen,
    analysisMode, setAnalysisMode,
    activeAdvancedProfile, setActiveAdvancedProfile,
    aiPreview, setAiPreview,
    pendingPositions, setPendingPositions,
    pendingViewport, setPendingViewport
  };
}
