/**
 * Shared State Machine Guards — graph integrity functions for CT and BB.
 *
 * Pure graph algorithms: accept graph + sets as parameters, no SM-specific coupling.
 * Used by NavigationEngine for:
 * - Prune validation (orphan guard, cascade guard)
 * - Node reference validation (reject hallucinated names)
 * - Bridge node injection (reconnect orphan noted nodes in result graph)
 *
 * All BFS operations are O(V+E) — fast even for 10K+ node graphs.
 *
 * Zero VS Code imports. No side effects.
 */

import type Graph from 'graphology';


/**
 * Logging callback injected into state machines for operational tracing.
 *
 * @remarks
 * Use 'trace' for the most verbose graph-level operations (e.g., individual BFS steps),
 * 'debug' for round-level state changes, and 'info' for phase transitions.
 */
export type LogFn = (level: 'info' | 'debug' | 'warn' | 'trace', msg: string) => void;


/**
 * Performs a BFS reachability check from a starting node, respecting a set of removed (pruned) nodes.
 *
 * @remarks
 * This function uses undirected traversal (graph.neighbors) to ensure that both upstream
 * and downstream nodes are correctly identified within the lineage scope. This is essential
 * because a node's relevance is often determined by its connection to source tables (inbound)
 * as well as target views (outbound).
 *
 * @param graph - The graphology instance to traverse.
 * @param startId - The ID of the node to start the BFS from.
 * @param removedSet - A set of node IDs that have been pruned and should be treated as non-existent.
 * @param candidateId - An optional candidate node ID to exclude from reachability (used for "what-if" analysis).
 * @param scope - An optional set of allowed node IDs to restrict the search.
 * @returns A set of all node IDs reachable from the start node.
 */
export function bfsReachable(
  graph: Graph,
  startId: string,
  removedSet: ReadonlySet<string>,
  candidateId?: string,
  scope?: ReadonlySet<string>,
): Set<string> {
  if (!graph.hasNode(startId)) return new Set();
  const reachable = new Set<string>([startId]);
  const queue = [startId];
  let idx = 0;
  while (idx < queue.length) {
    const id = queue[idx++];
    for (const nid of graph.neighbors(id)) {
      if (reachable.has(nid)) continue;
      if (removedSet.has(nid) || nid === candidateId) continue;
      if (scope && !scope.has(nid)) continue;
      reachable.add(nid);
      queue.push(nid);
    }
  }
  return reachable;
}


/**
 * Determines if pruning a candidate node would orphan any previously noted nodes from the origin.
 *
 * @remarks
 * This guard prevents the AI from accidentally cutting off access to nodes it has already
 * flagged as important ("noted") during an exploration.
 *
 * @param graph - The graphology instance to check.
 * @param originId - The ID of the exploration's origin node.
 * @param removedSet - The current set of pruned nodes.
 * @param notedIds - The set of nodes previously noted by the AI.
 * @param candidateId - The ID of the node being considered for pruning.
 * @returns The ID of the first orphaned noted node found, or `null` if no orphaning occurs.
 */
export function wouldOrphanNotedNode(
  graph: Graph,
  originId: string,
  removedSet: ReadonlySet<string>,
  notedIds: ReadonlySet<string>,
  candidateId: string,
): string | null {
  if (notedIds.size === 0) return null;
  const reachable = bfsReachable(graph, originId, removedSet, candidateId);
  for (const id of notedIds) {
    if (!reachable.has(id)) return id;
  }
  return null;
}

/**
 * Validates a list of node-related objects against a known node map.
 *
 * @remarks
 * Every node reference generated by the AI must be validated against the deterministic model
 * to prevent "hallucinated" node names from causing engine crashes or inconsistent state.
 *
 * @param nodeMap - The ground-truth map of all nodes in the current model.
 * @param entries - The list of objects containing node IDs to validate.
 * @returns An object containing arrays of valid and invalid entries, with reasons for the latter.
 */
export function validateNodeIds<T extends { nodeId: string }>(
  nodeMap: ReadonlyMap<string, unknown>,
  entries: T[],
): { valid: T[]; invalid: Array<T & { reason: string }> } {
  const valid: T[] = [];
  const invalid: Array<T & { reason: string }> = [];
  for (const entry of entries) {
    if (nodeMap.has(entry.nodeId)) {
      valid.push(entry);
    } else {
      invalid.push({ ...entry, reason: `"${entry.nodeId}" does not exist in the model` });
    }
  }
  return { valid, invalid };
}


/**
 * Represents a node injected into the result graph to bridge gaps between disconnected components.
 */
export interface BridgeNode {
  /** The unique identifier of the bridge node. */
  id: string;
  /** The SQL schema name. */
  schema: string;
  /** The short object name. */
  name: string;
  /** The object type (e.g., 'table', 'view'). */
  type: string;
}

/**
 * Contains the results of a bridge node injection operation.
 */
export interface BridgeResult {
  /** The list of intermediate nodes found to reconnect orphans. */
  bridgeNodes: BridgeNode[];
  /** The list of directed edges required to form the bridge paths. */
  bridgeEdges: Array<[string, string, string]>;
  /** The total number of noted nodes that were initially disconnected. */
  orphanCount: number;
  /** The number of noted nodes successfully reconnected. */
  reconnectedCount: number;
}

/**
 * Identifies orphan noted nodes and calculates the shortest paths required to reconnect them to the origin.
 *
 * @remarks
 * During exploration, the AI might mark intermediate nodes as "prune," which can break
 * the connectivity of the final result graph. This function performs "Bridge Injection"
 * by finding the shortest path through the full graph to reconnect these important orphans,
 * ensuring the final visualization remains structurally sound.
 *
 * @param graph - The full graphology instance.
 * @param notedIds - The set of node IDs that must appear in the final result.
 * @param resultEdges - The current list of edges already included in the result.
 * @param edgeTypeMap - A map of edge keys to their respective types for directed reconstruction.
 * @returns A `BridgeResult` containing the necessary nodes and edges to restore connectivity.
 */
export function findBridgeNodes(
  graph: Graph,
  notedIds: ReadonlySet<string>,
  resultEdges: ReadonlyArray<[string, string, string]>,
  edgeTypeMap: ReadonlyMap<string, string>,
): BridgeResult {
  // Identify nodes that participate in at least one result edge
  const edgeParticipants = new Set<string>();
  for (const [s, t] of resultEdges) {
    edgeParticipants.add(s);
    edgeParticipants.add(t);
  }

  // Orphans = noted nodes with zero edges in the result
  const orphans = [...notedIds].filter(id => !edgeParticipants.has(id));
  if (orphans.length === 0) return { bridgeNodes: [], bridgeEdges: [], orphanCount: 0, reconnectedCount: 0 };

  const bridgeNodes: BridgeNode[] = [];
  const bridgeEdges: Array<[string, string, string]> = [];
  const addedBridgeIds = new Set<string>();
  const addedEdgeKeys = new Set<string>();
  let reconnected = 0;

  for (const orphanId of orphans) {
    // BFS from orphan to nearest node in edgeParticipants (the connected component)
    const path = bfsShortestPath(graph, orphanId, edgeParticipants, edgeTypeMap);
    if (!path) continue; // truly disconnected — no path exists
    reconnected++;

    // Add intermediate bridge nodes
    for (const nodeId of path.intermediates) {
      if (!addedBridgeIds.has(nodeId) && !notedIds.has(nodeId)) {
        addedBridgeIds.add(nodeId);
        if (graph.hasNode(nodeId)) {
          const attrs = graph.getNodeAttributes(nodeId);
          bridgeNodes.push({
            id: nodeId,
            schema: (attrs.schema as string) ?? '',
            name: (attrs.name as string) ?? nodeId.split('.').pop()?.replace(/[\[\]]/g, '') ?? nodeId,
            type: (attrs.type as string) ?? 'unknown',
          });
        }
      }
    }

    // Add edges along the path — already in correct directed order from bfsShortestPath
    for (const [s, t] of path.edgePairs) {
      const key = `${s}→${t}`;
      if (!addedEdgeKeys.has(key)) {
        addedEdgeKeys.add(key);
        const type = edgeTypeMap.get(key) ?? 'read';
        bridgeEdges.push([s, t, type]);
      }
    }
  }

  return { bridgeNodes, bridgeEdges, orphanCount: orphans.length, reconnectedCount: reconnected };
}


/**
 * Generates a depth map for a directed graph starting from an origin node.
 *
 * @remarks
 * This function calculates the minimum hop distance from the origin to all reachable nodes
 * in a result subgraph. It is primarily used to sort nodes into "stages" or "tiers" for
 * structured report generation and visualization layout.
 *
 * @param edges - A flat list of directed edges [source, target, type].
 * @param originNodeId - The root node from which to calculate depths (depth 0).
 * @returns A map of node IDs to their respective depth. Unreachable nodes are excluded.
 */
export function bfsDepthMap(
  edges: ReadonlyArray<readonly [string, string, string]>,
  originNodeId: string,
): Map<string, number> {
  // Build adjacency list (directed: source → targets)
  const adj = new Map<string, string[]>();
  for (const [s, t] of edges) {
    let targets = adj.get(s);
    if (!targets) { targets = []; adj.set(s, targets); }
    targets.push(t);
  }

  const depth = new Map<string, number>();
  depth.set(originNodeId, 0);
  const queue = [originNodeId];
  let idx = 0;
  while (idx < queue.length) {
    const id = queue[idx++];
    const d = depth.get(id)!;
    for (const nid of adj.get(id) ?? []) {
      if (depth.has(nid)) continue;
      depth.set(nid, d + 1);
      queue.push(nid);
    }
  }
  return depth;
}


/**
 * BFS shortest path from startId to any node in targetSet.
 * Returns intermediate nodes + edge pairs in correct directed order (via edgeTypeMap lookup).
 * Undirected traversal via graph.neighbors — finds path regardless of edge direction.
 */
function bfsShortestPath(
  graph: Graph,
  startId: string,
  targetSet: ReadonlySet<string>,
  edgeTypeMap: ReadonlyMap<string, string>,
): { intermediates: string[]; edgePairs: Array<[string, string]> } | null {
  if (targetSet.has(startId)) return { intermediates: [], edgePairs: [] };
  if (!graph.hasNode(startId)) return null;

  const parent = new Map<string, string>();
  const queue = [startId];
  parent.set(startId, '');
  let idx = 0;

  while (idx < queue.length) {
    const id = queue[idx++];
    if (!graph.hasNode(id)) continue;
    for (const nid of graph.neighbors(id)) {
      if (parent.has(nid)) continue;
      parent.set(nid, id);
      if (targetSet.has(nid)) {
        // Reconstruct path: startId → ... → nid
        const intermediates: string[] = [];
        const edgePairs: Array<[string, string]> = [];
        let cur = nid;
        while (cur !== startId) {
          const prev = parent.get(cur)!;
          // Emit edge in actual directed order — not BFS traversal order
          if (edgeTypeMap.has(`${prev}→${cur}`)) {
            edgePairs.unshift([prev, cur]);
          } else {
            edgePairs.unshift([cur, prev]); // actual directed edge is cur→prev
          }
          if (cur !== nid && cur !== startId) intermediates.push(cur);
          cur = prev;
        }
        return { intermediates, edgePairs };
      }
      queue.push(nid);
    }
  }
  return null; // no path exists
}
