import { memo, useState } from 'react';
import type { FilterProfile } from '../engine/projectStore';
import { AI_COLOR_HEX } from '../utils/schemaColors';
import { Tooltip } from './ui/Tooltip';

interface BookmarkInfoCardProps {
  profile: FilterProfile;
  staleNodeNames: string[];
}

const SOURCE_DESCRIPTIONS: Record<NonNullable<FilterProfile['source']>, string> = {
  ai: 'AI-generated by @lineage',
  trace: 'From trace',
  analysis: 'From analysis',
  user: 'Saved view',
};


export const BookmarkInfoCard = memo(function BookmarkInfoCard({
  profile,
  staleNodeNames,
}: BookmarkInfoCardProps) {
  const [collapsed, setCollapsed] = useState(false);

  const createdAt = new Date(profile.createdAt).toLocaleString(undefined, {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  const source = profile.source ?? 'user';
  const hasSummary = !!profile.aiMetadata?.summary;
  const hasGroups = (profile.aiMetadata?.highlightGroups?.length ?? 0) > 0;
  const hasStale = staleNodeNames.length > 0;

  return (
    <div
      className="ln-bookmark-info-card"
      style={{
        position: 'absolute',
        bottom: 40,
        left: 12,
        zIndex: 5,
        minWidth: 180,
        maxWidth: 320,
        width: 'fit-content',
        maxHeight: 'min(60vh, 400px)',
        overflowY: 'auto',
        overflowX: 'hidden',
        pointerEvents: 'auto',
      }}
    >
      {/* Header row */}
      <button
        className="w-full flex items-center justify-between px-3 py-2 cursor-pointer border-0"
        onClick={() => setCollapsed(c => !c)}
        style={{ background: 'none', borderBottom: collapsed ? 'none' : '1px solid var(--ln-border-light)', textAlign: 'left' }}
        aria-expanded={!collapsed}
        aria-label="Toggle view info"
      >
        <span className="text-[10px] font-semibold ln-text-muted uppercase tracking-wide">
          View Info
        </span>
        <span className="text-[10px] ln-text-muted">{collapsed ? '▲' : '▼'}</span>
      </button>

      {!collapsed && (
        <div className="px-3 pb-3 flex flex-col gap-1.5">
          {/* Created */}
          <div className="flex flex-col">
            <span className="text-[9px] ln-text-muted uppercase tracking-wide">Created</span>
            <span className="text-[10px] ln-text">{createdAt}</span>
          </div>

          {/* Source */}
          <div className="flex flex-col">
            <span className="text-[9px] ln-text-muted uppercase tracking-wide">Source</span>
            <span className="text-[10px] ln-text">{SOURCE_DESCRIPTIONS[source]}</span>
          </div>

          {/* Summary (AI views) */}
          {hasSummary && (
            <div className="flex flex-col">
              <span className="text-[9px] ln-text-muted uppercase tracking-wide">Summary</span>
              <Tooltip content={profile.aiMetadata!.summary} placement="right" multiline maxWidth={400} delay={300}>
                <span
                  className="text-[10px] ln-text ln-narrative-clamp"
                  style={{ lineHeight: 1.4 }}
                >
                  {profile.aiMetadata!.summary}
                </span>
              </Tooltip>
            </div>
          )}

          {/* Highlight groups legend (AI views) */}
          {hasGroups && (
            <div className="flex flex-col gap-0.5">
              <span className="text-[9px] ln-text-muted uppercase tracking-wide">Groups</span>
              {profile.aiMetadata!.highlightGroups.map((g, i) => (
                <div key={i} className="flex items-center gap-1.5">
                  <span
                    style={{
                      width: 8,
                      height: 8,
                      borderRadius: '50%',
                      background: AI_COLOR_HEX[g.color] ?? AI_COLOR_HEX.gy,
                      flexShrink: 0,
                    }}
                  />
                  <Tooltip content={g.label} asChild><span className="text-[10px] ln-text truncate">{g.label}</span></Tooltip>
                </div>
              ))}
            </div>
          )}

          {/* Stale objects warning */}
          {hasStale && (
            <div
              className="text-[9px] rounded px-2 py-1.5"
              style={{
                background: 'var(--ln-validation-warning-bg)',
                border: '1px solid var(--ln-validation-warning-border)',
                color: 'var(--ln-validation-warning-fg)',
              }}
            >
              <span className="font-semibold">⚠ Not found: </span>
              {staleNodeNames.join(', ')}
            </div>
          )}
        </div>
      )}
    </div>
  );
});
