import { memo, useState } from 'react';
import type { FilterProfile } from '../engine/projectStore';

interface BookmarkInfoCardProps {
  profile: FilterProfile;
  /** Number of nodes currently in the graph for this view. */
  nodeCount: number;
  /** Number of distinct schemas in the current view. */
  schemaCount: number;
  staleNodeNames: string[];
}

const SOURCE_DESCRIPTIONS: Record<NonNullable<FilterProfile['source']>, string> = {
  ai: 'AI-generated by @lineage',
  trace: 'From trace',
  analysis: 'From analysis',
  user: 'Saved view',
};

/** Format ISO date to short locale string — "Mar 29, 2026, 12:15" */
function formatDate(iso: string): string {
  return new Date(iso).toLocaleString(undefined, {
    month: 'short', day: 'numeric', year: 'numeric',
    hour: '2-digit', minute: '2-digit',
  });
}

export const BookmarkInfoCard = memo(function BookmarkInfoCard({
  profile,
  nodeCount,
  schemaCount,
  staleNodeNames,
}: BookmarkInfoCardProps) {
  const [collapsed, setCollapsed] = useState(false);

  const source = profile.source ?? 'user';
  const ai = profile.aiMetadata;
  const hasStale = staleNodeNames.length > 0;

  return (
    <div
      className="ln-bookmark-info-card"
      style={{
        position: 'absolute',
        bottom: 40,
        left: 12,
        zIndex: 5,
        minWidth: 180,
        maxWidth: 320,
        width: 'fit-content',
        maxHeight: 'min(60vh, 400px)',
        overflowY: 'auto',
        overflowX: 'hidden',
        pointerEvents: 'auto',
      }}
    >
      {/* Header row */}
      <button
        className="w-full flex items-center justify-between px-3 py-2 cursor-pointer border-0"
        onClick={() => setCollapsed(c => !c)}
        style={{ background: 'none', borderBottom: collapsed ? 'none' : '1px solid var(--ln-border-light)', textAlign: 'left' }}
        aria-expanded={!collapsed}
        aria-label="Toggle view info"
      >
        <span className="text-[10px] font-semibold ln-text-muted uppercase tracking-wide">
          View Info
        </span>
        <span className="text-[10px] ln-text-muted">{collapsed ? '▲' : '▼'}</span>
      </button>

      {!collapsed && (
        <div className="px-3 pb-3 flex flex-col gap-1.5">
          {/* Stats — auto-generated */}
          <div className="flex flex-col">
            <span className="text-[9px] ln-text-muted uppercase tracking-wide">Scope</span>
            <span className="text-[10px] ln-text">{nodeCount} objects, {schemaCount} schemas</span>
          </div>

          {/* Source */}
          <div className="flex flex-col">
            <span className="text-[9px] ln-text-muted uppercase tracking-wide">Source</span>
            <span className="text-[10px] ln-text">{SOURCE_DESCRIPTIONS[source]}</span>
          </div>

          {/* Created + Model — AI views show model name, others show date only */}
          <div className="flex flex-col">
            <span className="text-[9px] ln-text-muted uppercase tracking-wide">Created</span>
            <span className="text-[10px] ln-text">
              {formatDate(ai?.createdAt ?? profile.createdAt)}
              {ai?.modelName && <span className="ln-text-muted"> by {ai.modelName}</span>}
            </span>
          </div>

          {/* Stale objects warning */}
          {hasStale && (
            <div
              className="text-[9px] rounded px-2 py-1.5"
              style={{
                background: 'var(--ln-validation-warning-bg)',
                border: '1px solid var(--ln-validation-warning-border)',
                color: 'var(--ln-validation-warning-fg)',
              }}
            >
              <span className="font-semibold">Not found: </span>
              {staleNodeNames.join(', ')}
            </div>
          )}
        </div>
      )}
    </div>
  );
});
